### ISSUE TITLE
wardley-maps CLI?

### ISSUE THREAD

**Issue by jLouzado** [wardley-maps-community/awesome-wardley-maps#14]
- Is there a cli-tool or package that would take a UML representation like and generate a map of it?
- basically https://onlinewardleymaps.com/, but available as a command line tool

**Comment by jhngrant** [comment]
Go-Wardley by @DavidGamba takes an HCL based map description and generates a Wardley map in SVG format.

https://github.com/DavidGamba/go-wardley

**Comment by jLouzado** [comment]
beautiful... thank you :)

**Comment by jLouzado** [comment]
maybe this can be added in the main document itself?

**Comment by jLouzado** [comment]
> Go-Wardley by @DavidGamba takes an HCL based map description and generates a Wardley map in SVG format.
> 
> https://github.com/DavidGamba/go-wardley

**Comment by jhngrant** [comment]
Added:
https://github.com/wardley-maps-community/awesome-wardley-maps/blob/master/README.md#apps
