### ISSUE TITLE
Quick Start

### ISSUE THREAD

**Issue by jhngrant** [wardley-maps-community/awesome-wardley-maps#8]
I’d like to propose a new section, Quick Start, aimed at people new to mapping with limited time (between 5-10 mins).

The objectives are:

- Provide a *brief* and balanced overview of Wardley mapping and its benefits
- Community onboarding

I’m a listener and a visual person so biased towards multimedia. Here's my candidate list for the new section:

- Mike Lamb: Investing in innovation - How situational awareness can put your business on the map (5:51)
https://www.youtube.com/watch?v=Gfq3ocmadZo&list=PLP0vnsXbJsRUlwyS73DlT8CWSkN33J-JY
- Sue Borchardt: Getting Strategic on Peace and Justice (5:39)
https://vimeo.com/363571089
- Simon Wardley: How Mapping helps you make strategic plays (2:12)
https://www.youtube.com/watch?v=9G9dK55wpvw&list=PLP0vnsXbJsRWQoyt4AHi3AjC02c61PHaG

For the list to be useful, input from others is essential. So, what should we include in this “Quick Start” section?

**Comment by jhngrant** [comment]
Twitter comments: https://twitter.com/lcooney/status/1207665776775155712

**Comment by johnthompson365** [comment]
I think it is a good idea. Is this 'quick start' to using the community, or 'quick start' to creating a map?
